---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-5.10
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - 'recipe[389ds::default]'
  - name: server
    run_list:
      - 'recipe[389ds::server]'
